[package]
name = "polodb-c-exporter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
polodb_core = { path = "../../../src/polodb_core" }
serde_json = "1"